#!/bin/bash
#Script auto create user SSH

echo -e "-------------------------------- MEMBUAT AKUN SSH --------------------------------"
echo -e "                         ALL SUPPORTED BY SuperSSH                     "
echo -e "                      https://telegram.me/Supersshgrup"
echo -e "  Script by. Fauzy Spr (https://www.facebook.com/fauzy.sprssh , 087883575384)"

echo -e ""

read -p "Username : " Login
read -p "Password : " Pass
read -p "Expired (hari): " masaaktif

IP=`dig +short myip.opendns.com @resolver1.opendns.com`
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M thornssh-$Login
exp="$(chage -l thornssh-$Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd thornssh-$Login &> /dev/null
echo -e ""
echo -e "|      Informasi Akun Baru SSH      |"
echo -e "=========================================="
echo -e "Host: $IP" 
echo -e "Port OpenSSH: 22,143"
echo -e "Port Dropbear: 80,109,110443"
echo -e "Squid: 8080,3128"
echo -e "Username: $Login "
echo -e "Password: $Pass"
echo -e "NO Multi Login"
echo -e "-------------------------------------------"
echo -e "Aktif Sampai: $exp"
echo -e "=========================================="
echo -e "DILARANG : DDOS/TORRENT/HACK/ILEGAL CONTENT"
echo -e "=========================================="
echo -e "Config OpenVPN (TCP 1194)"
echo -e "http://$IP:81/client.ovpn"
echo -e "-------------------------------------------"

echo -e ""
