#!/bin/bash
#Menu
IP=`dig +short myip.opendns.com @resolver1.opendns.com`
echo -e "------------ Selamat datang di server $IP -----------"
echo -e "Terimakasih telah menggunakan Script kami"
echo -e ""
echo -e "-------------------------------- Daftar Menu --------------------------------"
echo -e "Apa yang ingin anda lakukan?"
echo -e "1)  Membuat akun SSH/OpenVpn	- (usernew)"
echo -e "2)  Membuat akun trial	- (trial)"
echo -e "3)  Hapus akun SSH	- (hapus)"
echo -e "4)  Monitoring	- (login)"
echo -e "5)  Dropmon - (dropmon)"
echo -e "6)  Banned akun expired	- (user-expired)"
echo -e "7)  All Akun SSH	- (member)"
echo -e "8)  Restart All	- (restart)"
echo -e "9) Speedtest VPS	- (speedtest)"
echo -e "10) Cek Kualitas VPS	- (bench-network)"
echo -e "11) Cek RAM VPS	- (ps-mem)"
echo -e "12) informasi tentang script auto install	- (about)"
echo -e "-------------------------------- SuperSSH --------------------------------"
read -p "ketik yg ingin anda lakukan : " Nama

-R $Nama

echo -e ""
