#!/bin/bash
#TrialSSH
#Aktif 1 hari
#modified by SuperSSH

IP=`dig +short myip.opendns.com @resolver1.opendns.com`

Login=trial`</dev/urandom tr -dc X-Z0-9 | head -c4`
hari="1"
Pass=`</dev/urandom tr -dc a-f0-9 | head -c9`

useradd -e `date -d "$hari days" +"%Y-%m-%d"` -s /bin/false -M SuperSSH-$Login
echo -e "$Pass\n$Pass\n"|passwd SuperSSH-$Login &> /dev/null
echo -e ""
echo -e "-------------------------------- MEMBUAT TRIAL AKUN SSH --------------------------------"
echo -e "                         ALL SUPPORTED BY SuperSSH                     "
echo -e "                      https://telegram.me/Supersshgrup"
echo -e "  Script by. Fauzy Spr (https://www.facebook.com/fauzy.sprssh , 087883575384)"

echo -e "|      Informasi Akun Baru SSH      |"
echo -e "=========================================="
echo -e "Host: $IP" 
echo -e "Port OpenSSH: 22,80"
echo -e "Port Dropbear: 143,443,109,110"
echo -e "Username: SuperSSH-$Login"
echo -e "Password: $Pass\n"
echo -e "NO Multi Login"
echo -e "-------------------------------------------"
echo -e "Aktif Sampai: $exp"
echo -e "=========================================="
echo -e "DILARANG : DDOS/TORRENT/HACK/ILEGAL CONTENT"
echo -e "==========================================="
echo -e "Config OVPN (TCP 1194): http://"
echo -e "http://$IP:81/client.ovpn"
echo -e "-------------------------------------------"

echo -e ""
